name: 🚀 Deploy Blame Game to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy_reason:
        description: 'Reason for manual deployment'
        required: false
        default: 'Manual deployment'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "deployment-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  pre-deploy-checks:
    name: 🔍 Pre-deployment Checks
    runs-on: ubuntu-latest
    outputs:
      needs-translation: ${{ steps.translation-check.outputs.needs-translation }}
      
    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: 📥 Install Dependencies
        run: |
          echo "📥 Installing dependencies with lockfile validation..."
          # Try frozen lockfile first, fallback to updating if needed
          if ! pnpm install --frozen-lockfile; then
            echo "⚠️ Lockfile mismatch detected, updating dependencies..."
            pnpm install
            echo "✅ Dependencies updated successfully"
          else
            echo "✅ Dependencies installed from frozen lockfile"
          fi

      - name: 🔍 Check Translation Status
        id: translation-check
        run: |
          echo "🔍 Checking if translations are needed..."
          if [ -f "scripts/auto-translate.js" ]; then
            # Check if there are missing translations
            node scripts/auto-translate.js --check-only || echo "needs-translation=true" >> $GITHUB_OUTPUT
          else
            echo "needs-translation=false" >> $GITHUB_OUTPUT
          fi

  build-and-deploy:
    name: 🏗️ Build and Deploy
    runs-on: ubuntu-latest
    needs: pre-deploy-checks
    environment:
      name: github-pages
      url: https://blamegame.leagueoffun.de
    
    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: 📥 Install Dependencies
        run: |
          echo "📥 Installing dependencies with lockfile validation..."
          # Try frozen lockfile first, fallback to updating if needed
          if ! pnpm install --frozen-lockfile; then
            echo "⚠️ Lockfile mismatch detected, updating dependencies..."
            pnpm install
            echo "✅ Dependencies updated successfully"
          else
            echo "✅ Dependencies installed from frozen lockfile"
          fi

      - name: 🌐 Auto-translate if needed
        if: needs.pre-deploy-checks.outputs.needs-translation == 'true'
        run: |
          echo "🔄 Running translation system..."
          pnpm run translate
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        continue-on-error: true

      - name: 🛠️ Build Project
        run: |
          echo "🏗️ Building project..."
          pnpm run build:domain

      - name: 🔧 Ensure GitHub Pages Compatibility
        run: |
          echo "🔧 Ensuring GitHub Pages compatibility..."
          
          # Ensure .nojekyll file exists to disable Jekyll processing
          if [ ! -f "./dist/.nojekyll" ]; then
            echo "📝 Adding .nojekyll file to disable Jekyll processing"
            touch ./dist/.nojekyll
          fi
          
          # Verify essential JSON files are present
          echo "🔍 Verifying JSON files are included in build..."
          if [ -f "./dist/questions/categories.json" ]; then
            echo "✅ categories.json found"
          else
            echo "❌ categories.json missing - this will cause loading issues!"
            exit 1
          fi
          
          if [ -d "./dist/questions/de" ]; then
            question_count=$(find ./dist/questions/de -name "*.json" | wc -l)
            echo "✅ German questions found: $question_count files"
          else
            echo "❌ German questions directory missing!"
            exit 1
          fi
          
          # List all files for debugging
          echo "📁 Build directory contents:"
          find ./dist -type f | head -20

      - name: ⚙️ Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: ⬆️ Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          timeout: 600000  # 10 minutes timeout

      - name: ✅ Verify Deployment
        run: |
          echo "🔍 Verifying deployment..."
          
          # Wait for propagation
          sleep 30
          
          # Check if main site is accessible
          if curl -f -s --max-time 30 "https://blamegame.leagueoffun.de/" > /dev/null; then
            echo "✅ Site is accessible!"
            
            # Wait a bit more and check JSON files
            sleep 30
            if curl -f -s --max-time 30 "https://blamegame.leagueoffun.de/questions/categories.json" > /dev/null; then
              echo "✅ JSON files are accessible!"
              echo "🌐 Deployment fully verified at: https://blamegame.leagueoffun.de/"
            else
              echo "⚠️ JSON files not yet accessible, but main site is up"
              echo "This might be due to CDN propagation delay"
            fi
          else
            echo "⚠️ Site not immediately accessible, this might be normal"
            echo "CDN propagation can take a few minutes"
          fi

      - name: 📊 Deployment Report
        if: always()
        run: |
          echo "## 🚀 Deployment Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- 🏗️ **Build Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- 🚀 **Deployment**: ${{ steps.deployment.outcome }}" >> $GITHUB_STEP_SUMMARY
          echo "- 🌐 **Site URL**: https://blamegame.leagueoffun.de/" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "_Deployment completed using simplified GitHub Pages action._" >> $GITHUB_STEP_SUMMARY
