name: 🚀 Deploy Blame Game to GitHub Pages

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch

jobs:
  build-and-deploy:
    name: 🏗️ Build and Deploy
    runs-on: ubuntu-latest
    permissions: # Necessary permissions for GitHub Pages deployment
      contents: read
      pages: write
      id-token: write
    environment: # Configure the deployment environment for GitHub Pages
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4 # Updated to v4

      - name: 🧹 Remove pnpm-workspace.yaml (if exists)
        run: rm -f pnpm-workspace.yaml
        shell: bash

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v3 # Updated to v3
        with:
          version: 9 # Changed from 8 to 9 to match lockfileVersion '9.0'

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4 # Updated to v4
        with:
          node-version: '18'
          # Removed pnpm cache configuration as it's causing issues

      - name: ⚙️ Install Dependencies
        run: pnpm install --no-frozen-lockfile # Changed to --no-frozen-lockfile to bypass lockfile issues

      - name: 🎨 Lint Code
        run: pnpm run lint -- --max-warnings=9999

      - name: 🧐 Type-Check Code
        run: pnpm run typecheck

      - name: 🛠️ Build Project
        run: pnpm run build

      - name: ⚙️ Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: ⬆️ Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Path to the directory to upload

      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
