name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: # Added permissions for GitHub Pages deployment
      contents: read
      pages: write
      id-token: write
    environment: # Added environment for GitHub Pages
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Corrected order: Install pnpm BEFORE setting up Node.js with pnpm caching
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # Specify your pnpm version

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify your Node.js version
          cache: 'pnpm' # Configure caching for pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Type-check
        run: pnpm run typecheck

      - name: Build
        run: pnpm run build

      - name: Setup Pages # Added step to configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact # Added step to upload build artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'

      - name: Deploy to GitHub Pages # Modified deployment step
        id: deployment
        uses: actions/deploy-pages@v2
